### ISSUE TITLE
How to switch video quality

### ISSUE THREAD

**Issue by anphunl** [viki-org/VKVideoPlayer#44]
I have a HLS link (m3u8) with different video quality stream inside. How can I change the video quality?

Thank you very much!

**Comment by jarrold** [comment]
Hi @anphunl according to the HLS spec, if you have set it up right, it should switch by itself depending on  the bandwidth.

Here are some things that I found out that might help someone else:

1. How do you determine which stream is currently being played by the player? avplayer.currentItem.accessLog.events.lastObject.URI (can’t believe I couldn’t find this out had to read the documentation 3 times before figuring this one out, we actually resorting to burning the stream names into the video files itself to test)

2. What is the bitrate / bandwidth that the player is seeing / using / reporting / observing? avplayer.currentItem.accessLog.events.lastObject.observedBitrate (AVAssetTrack.estimatedDataRate lead me on a wild goose chase…)

3. What are the rules for switching between streams? avplayer.currentItem.accessLog.events.lastObject.indicatedBitrate will be the bitrate that you define in your playlist which is paired with each stream. So what I have observed (this was done purely by using Network Link Conditioner to modify my network bandwidth and see which stream was played, not at all scientific) the player will play the default stream (first stream in playlist) and will start observing the bitrate. Once the observed bitrate increases to twice of the next stream’s indicated bitrate, it will switch to that next stream and will remain there until it drops below that indicated bitrate or if it becomes twice the next one, it will switch up again.

This meant a couple of things:

* Chose your indicatedBitrate carefully. Let’s assume the Network Link Conditioner’s profiles are correct and that for an average 3G connection the bandwidth is 780kbps, from what I observed the player only really gets 680kpbs so if your stream was indicated as 380kpbs, there is a high chance that someone on an average 3G connection will never be able to play it despite getting as high as 680kbps (will need 760kbps observedbitrate to switch up). So take note of the different network conditions like Edge, 3G and LTE and encode accordingly.

* Have more streams to cater to lower bandwidth connections rather that having them equally spaced out. With more people getting cable network speeds, having more streams above 500kpbs doesn’t seem to make a difference visually on the device (airplay is another story). Once users go on Wifi, they can get 2Mbps which would give them really good quality video. The devices that really benefit from HLS are those with low bandwidth and lossy connection. This is where HLS really shines. So have more streams to cater for Edge to 3G instead of 3G to Wifi.

**Comment by anphunl** [comment]
Thank @jarrold  very much for your answer.

Currently, my solution is 
* If user play a HSL stream, its quality will be switched automatically based on network
* I also parse the m3u8 file to find all URL for each stream, so that users can select it manually. When they change the stream, I start a new video as normal and after that seek to the last played time.

**Comment by mohpor** [comment]
That was some really fine points. Thanks

**Comment by jarrold** [comment]
@anphunl for us, we also allow our users to select the stream manually, but instead of finding the URL for each stream, we actually have mp4 streams that we have encoded for other platforms and we reload the player with the selected mp4 stream and seek to the last played time, similar to your solution :)
